kind: Service
apiVersion: v1
metadata:
  name: magicbox-app-service
spec:
  selector:
    app: magicbox-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magicbox-app-deployment
  labels:
    app: magicbox-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magicbox-app
  template:
    metadata:
      labels:
        app: magicbox-app
    spec:
      containers:
      - name: magicbox-app
        image: mikefab/magicbox-app:6dffae015ff81cbd20a360ad50811fefb1d06a7f
        #${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
